# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-22 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='description',
            field=models.TextField(blank=True, help_text='Zwischen 150 und 1000 Zeichen lang halten. Wichtig für Suchmaschinenindexierung.', verbose_name='site description'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.FileField(blank=True, help_text='Provide an image (Windows icon image, 16 x 16 pixels) which is used in browser bookmarks and such.', upload_to='uploads', verbose_name='favicon'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='inactive_image',
            field=models.ImageField(blank=True, help_text='Provide an image that will be displayed when the site is inactive', upload_to='uploads', verbose_name='inactive image'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='keywords',
            field=models.TextField(blank=True, help_text='Kommasepariert. Wichtig für Suchmaschinenindexierung.', verbose_name='site keywords'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='require_login',
            field=models.CharField(blank=True, choices=[('yes', 'login required'), ('staff', 'staff login required')], help_text='Choose if a valid login is needed to view this site', max_length=10, verbose_name='require login'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site_settings', to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_topic',
            field=models.TextField(blank=True, help_text='Zwischen 150 und 1000 Zeichen lang halten. Wichtig für Suchmaschinenindexierung.', verbose_name='site topic'),
        ),
    ]
